name: Check library

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "great_ai/**"
      - ".github/workflows/*"

jobs:
  lint:
    uses: ./.github/workflows/generic-lint-python.yml
    with:
      path_to_project: examples/complex

  sonar:
    needs: lint
    uses: ./.github/workflows/generic-sonarqube-python.yml
    with:
      project_name: great_ai
      path_to_project: examples/complex
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonar_host: ${{ secrets.SONAR_HOST_URL }}
